@startuml
actor Customer as c

package "Manufacturing & Distribution" as MD {
  usecase "Color" as color #lightblue
  usecase "Inventory" as inv #lightblue
  usecase "Logistics" as log #lightblue
  usecase "Manufacturing" as man #lightblue
  usecase "Procurement" as proc #lightblue
  usecase "Product" as prod #lightblue
  usecase "Product Information" as pi #lightblue
  usecase "Sales Order" as so #lightblue
  usecase "Supplier" as sup #lightblue
}

package "Sales & Marketing" as sm {
  usecase "Customer" as cust #lightblue
  usecase "Marketing" as market #lightblue
  usecase "Sales" as sales #lightblue
}

c --> so #blue;line.dotted;text:blue : Submits
c <-- market #blue;line.dotted;text:blue : Targets
market --> cust : Creates
cust --> sales : Generates
log --> inv : Transports
so --> inv : Consumes
so --> man : Generates
so --> prod :  References
prod --> pi : Uses
so --> proc : Uses
prod <-- man : Uses
sup --> proc : Fulfills
man --> inv : Generates
so --> log : Uses
sales --> so : Submits
@enduml