direction: right
Workforce: {
    Worker: {
      Employee: {
        shape: person
        style.multiple: true
      }
      Contractor: {
        shape: person
        style.multiple: true
      }
      Supervisor: {
        shape: person
        style.multiple: true
      }
      Employee -> Supervisor: Has|Is A
      Contractor -> Supervisor: Has A      
    }
    Worker -> Work Structure: Within

    Active Directory: {
      User: {
        shape: person
        style.multiple: true
      }
    }
    
    Worker -> Salary: Has A
    Worker -> Address: Has A
    Active Directory -> Worker: Is An
    
  }