Workforce
Workforce.Worker
Workforce.Worker.Employee
Workforce.Worker.Contractor
Workforce.Worker.Retiree
Workforce.User
Workforce.User.Active Directory

Workforce.User -> Workforce.Worker: Is A

Customer