Sales and Marketing: {
    Customers: {
        shape: Person
    }
    Employees: {
        shape: Person
    }
    Sales Orders: {
        Order Request
        Order Fullfillment
        Work Orders
        Shipments
        Order Request -> Fullfillments: Generates
        Order Fullfillment -> Shipments: Generates
        Order Request -> Shipments: References
        Order Request -> Work Orders: Can Generate
        Order Fullfillment -> Work Orders: Can Generate
        Work Orders -> Shipments: Generates
    }
  
    Products

    Inventory

    Inventory -> Sales Orders: Consumes
    Customers -> Sales Orders: |md
     Submits 
     Order
     Requests
    |
    Sales Orders -> Customers: |md 
    Order 
    Status
    |
    Sales Orders -> Employees: |md 
    Tracks 
    Fullfillment 
    Status
    |
    Products -> Sales Orders: |md
    Products 
    Purchased
    |
}

